export enum ProductUnitType {
  PIECE = "piece",
  SQUARE_METER = "square-meter",
  KILOGRAM = "kilogram",
  GRAM = "gram",
  LITER = "liter",
  MILLILITER = "milliliter",
  PACK = "pack",
  BOX = "box",
  DOZEN = "dozen",
  PAIR = "pair",
  SET = "set",
  YARD = "yard",
  FOOT = "foot",
  INCH = "inch",
  GALLON = "gallon",
  PINT = "pint",
  QUART = "quart",
  TON = "ton",
  CUBIC_METER = "cubic-meter",
  CUBIC_FOOT = "cubic-foot",
  CUBIC_INCH = "cubic-inch",
  BUNDLE = "bundle",
  ROLL = "roll",
  SHEET = "sheet",
  TUBE = "tube",
  CONTAINER = "container",
  CASE = "case",
  CARTON = "carton",
  BOTTLE = "bottle",
  CAN = "can",
  JAR = "jar",
  BARREL = "barrel",
  TILE = "tile",
  PANEL = "panel",
  SLAB = "slab",
  BOARD = "board",
  STRIP = "strip",
  ROD = "rod",
  LENGTH = "length",
  REEL = "reel",
  BAG = "bag",
  PAIL = "pail",
  SACK = "sack",
  SPOOL = "spool",
}

export const ProductUnitLabelByType: Record<ProductUnitType, string> = {
  [ProductUnitType.PIECE]: "pc.",
  [ProductUnitType.SQUARE_METER]: "m²",
  [ProductUnitType.KILOGRAM]: "kg",
  [ProductUnitType.GRAM]: "g",
  [ProductUnitType.LITER]: "L",
  [ProductUnitType.MILLILITER]: "mL",
  [ProductUnitType.PACK]: "pack",
  [ProductUnitType.BOX]: "box",
  [ProductUnitType.DOZEN]: "doz.",
  [ProductUnitType.PAIR]: "pair",
  [ProductUnitType.SET]: "set",
  [ProductUnitType.YARD]: "yd",
  [ProductUnitType.FOOT]: "ft",
  [ProductUnitType.INCH]: "in",
  [ProductUnitType.GALLON]: "gal",
  [ProductUnitType.PINT]: "pt",
  [ProductUnitType.QUART]: "qt",
  [ProductUnitType.TON]: "ton",
  [ProductUnitType.CUBIC_METER]: "m³",
  [ProductUnitType.CUBIC_FOOT]: "ft³",
  [ProductUnitType.CUBIC_INCH]: "in³",
  [ProductUnitType.BUNDLE]: "bundle",
  [ProductUnitType.ROLL]: "roll",
  [ProductUnitType.SHEET]: "sheet",
  [ProductUnitType.TUBE]: "tube",
  [ProductUnitType.CONTAINER]: "container",
  [ProductUnitType.CASE]: "case",
  [ProductUnitType.CARTON]: "carton",
  [ProductUnitType.BOTTLE]: "bottle",
  [ProductUnitType.CAN]: "can",
  [ProductUnitType.JAR]: "jar",
  [ProductUnitType.BARREL]: "barrel",
  [ProductUnitType.TILE]: "tile",
  [ProductUnitType.PANEL]: "panel",
  [ProductUnitType.SLAB]: "slab",
  [ProductUnitType.BOARD]: "board",
  [ProductUnitType.STRIP]: "strip",
  [ProductUnitType.ROD]: "rod",
  [ProductUnitType.LENGTH]: "length",
  [ProductUnitType.REEL]: "reel",
  [ProductUnitType.BAG]: "bag",
  [ProductUnitType.PAIL]: "pail",
  [ProductUnitType.SACK]: "sack",
  [ProductUnitType.SPOOL]: "spool",
};
